name: llmifier
description: A CLI tool to extract project documentation into a single file optimized for LLMs.
version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.4.4
  args: ^2.4.0
  glob: ^2.1.3
  path: ^1.8.3
  meta: ^1.16.0
  yaml: ^3.1.3
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.15
  build_version: ^2.1.1
  lints: ^5.0.0
  test: ^1.24.0

executables:
  llmifier: main
